org: shashankbiplav
app: products-crud
service: products-crud
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  stage: dev
  environment:
    tableName: ${self:custom.tableName}
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["ProductsTable", "Arn"] }

# package:
#   individually: true

custom:
  tableName: ProductsTable

functions:
  getProduct:
    handler: src/handlers.getProduct
    events:
      - httpApi:
          path: /product/{productID}
          method: get

  createProduct:
    handler: src/handlers.createProduct
    events:
      - httpApi:
          path: /product
          method: post

  updateProduct:
    handler: src/handlers.updateProduct
    events:
      - httpApi:
          path: /product/{id}
          method: put

  deleteProduct:
    handler: src/handlers.deleteProduct
    events:
      - httpApi:
          path: /product/{id}
          method: delete

  listProduct:
    handler: src/handlers.listAllProducts
    events:
      - httpApi:
          path: /products
          method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: productID
            AttributeType: S
          - AttributeName: category
            AttributeType: S

        KeySchema:
          - AttributeName: productID
            KeyType: HASH
          - AttributeName: category
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false
